apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
  labels:
    app: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
        - name: shopping-app-cont
          image: mallikaroy/shopping-app:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/shopping"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mallika"
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-app-service
  labels:
    app: spring-boot-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000  # You can choose any available port in your cluster
  selector:
    app: shopping-app